mautrix/telegramgo

pkg/connector/client.go
pkg/connector/msgconv/converter.go
pkg/connector/msgconv/tomatrix.go
pkg/store/scoped_store.go

images: implement sending from Matrix -> Telegram

---

Dockerfile.v2.ci

dockerfile: add v2 CI

---

pkg/connector/client.go
pkg/connector/download/photo.go

user metadata: bridge profile updates

---

pkg/connector/client.go
pkg/connector/directdownload.go
pkg/connector/download/photo.go
pkg/connector/ids/media.go
pkg/connector/msgconv/tomatrix.go

media: support thumbnails

---

pkg/connector/telegram.go

chat metadata: bridge join/leave events TG -> Matrix

---

pkg/connector/chatinfo.go
pkg/connector/client.go
pkg/connector/config.go
pkg/connector/store/scoped_store.go
pkg/connector/store/upgrades/00-latest.sql
pkg/connector/store/upgrades/03-move-user-access-hash-to-table.sql
pkg/connector/telegram.go

store: move the access_hash and username to separate per-user table

---

go.mod
go.sum
pkg/connector/chatinfo.go
pkg/connector/client.go
pkg/connector/matrix.go
pkg/connector/telegram.go

read receipts: bridges TG <-> Matrix

---

cmd/mautrix-telegram/legacyprovisioning.go
cmd/mautrix-telegram/main.go

legacyprovisioning: implement SNC endpoints

---

pkg/connector/api.go
pkg/connector/chatinfo.go
pkg/connector/config.go
pkg/connector/media/transfer.go
pkg/connector/telegram.go

Support messages sent as channel

---

pkg/connector/backfill.go
pkg/connector/client.go
pkg/connector/config.go
pkg/connector/sync.go

takeout: use takeout to list dialogs once permission granted

---

pkg/connector/tomatrix.go

connector/tomatrix: fix replies

---

cmd/mautrix-telegram/legacymigrate.sql
cmd/mautrix-telegram/legacyprovisioning.go
cmd/mautrix-telegram/main.go
pkg/connector/chatinfo.go
pkg/connector/client.go
pkg/connector/directdownload.go
pkg/connector/ids/ids.go
pkg/connector/matrix.go
pkg/connector/matrixfmt/convert.go
pkg/connector/media/transfer.go
pkg/connector/startnewchat.go
pkg/connector/store/scoped_store.go
pkg/connector/store/upgrades/00-latest.sql
pkg/connector/store/upgrades/02-separate-user-channel-namespace.sql
pkg/connector/telegram.go

ids: handle users and channels possibly having overlapping IDs

---

cmd/mautrix-telegram/legacymigrate.go
pkg/connector/client.go
pkg/connector/config.go
pkg/connector/example-config.yaml
pkg/connector/matrix.go
pkg/connector/telegram.go

reactions: use allowed reactions when possible

---

pkg/connector/api.go
pkg/connector/client.go
pkg/connector/startnewchat.go
pkg/connector/store/scoped_store.go
pkg/connector/telegram.go

portal: handle self-leaves of groups

---

pkg/connector/client.go
pkg/connector/telegram.go

client: ignore messages in left channels

---

pkg/connector/directdownload.go
pkg/connector/media/transfer.go

media: default to JPEG MIME-type for direct-downloaded images

---

pkg/connector/client.go
pkg/connector/sync.go
pkg/connector/telegram.go

mute: sync from Telegram -> Matrix, local bridges -> Telegram

---

pkg/connector/backfill.go
pkg/connector/client.go
pkg/connector/config.go
pkg/connector/sync.go
pkg/connector/telegram.go

- **pins: handle (un)favourite tags from the network connector**
- **pins: bridge from Telegram -> Matrix**

pins: bridge from Telegram, and local to Telegram

---

pkg/connector/chatinfo.go
pkg/connector/client.go
pkg/connector/sync.go
pkg/connector/telegram.go

power levels: bridge rights for group chats

---

pkg/connector/backfill.go
pkg/connector/config.go
pkg/connector/sync.go
pkg/connector/telegram.go

backfill: implement marking read

---

pkg/connector/chatinfo.go
pkg/connector/client.go
pkg/connector/config.go
pkg/connector/telegram.go

power levels: prevent sending to blocked users

---

pkg/connector/client.go
pkg/connector/store/scoped_store.go

logout: delete user-specific state

---

pkg/connector/client.go
pkg/connector/config.go
pkg/connector/login.go
pkg/connector/telegram.go
pkg/connector/tomatrix.go
pkg/connector/util/util.go

user info: handle deleted users

---

pkg/connector/client.go
pkg/connector/telegram.go

connector: notify when call starts/ends

---

pkg/connector/tomatrix.go

connector/tomatrix: handle circular videos

---

pkg/connector/matrix.go

stickers: support sending

---

pkg/connector/client.go
pkg/connector/telegram.go

calls: fix notifications

---

pkg/connector/client.go

connector/client: add variable for logged in state

---

pkg/connector/media/transfer.go

connector/media: fix transferring non-lottie stickers

---

pkg/connector/tomatrix.go

connector/tomatrix: fix video captions

---

pkg/connector/matrix.go

connector/matrix: make error messages on message sends more human-readable

---

pkg/connector/ids/ids.go

connector/ids: fix MakeMessageID

---

pkg/connector/client.go
pkg/connector/config.go
pkg/connector/metadata.go

metadata: clear more things from user login metadata on auth error

---

pkg/connector/telegram.go

connector/edits: add better logging when parts change

---

pkg/connector/client.go

Previously, we were going into UNKNOWN_ERROR too aggressively

connector: send BAD_CREDENTIALS if error is an auth error

---

pkg/connector/telegram.go

connector: add stream order to new messages

---

pkg/connector/media/transfer.go
pkg/connector/tomatrix.go

connector/tomatrix: fix video stickers

---

pkg/connector/tomatrix.go

connector/tomatrix: add timeout for getting webpage preview

---

pkg/connector/loginphone.go
pkg/connector/loginqr.go

login: fix contexts

---

pkg/connector/loginphone.go

connector/login: fix a context issue on phone number login

---

pkg/connector/emojis/emojis.go
pkg/connector/reactions.go
pkg/connector/telegram.go
pkg/connector/telegramfmt/convert.go
pkg/connector/telegramfmt/html.go
pkg/connector/telegramfmt/tags.go

emojis: properly handle inline emojis on local

---

pkg/connector/store/scoped_store.go

store: make finding by username case-insensitive

---

pkg/connector/backfill.go

backfill: add stream order

---

pkg/connector/startnewchat.go

Endpoint doesn't expect an error when the lookup is valid and just doesn't match a user: https://github.com/mautrix/telegramgo/blob/28d827655466094663bdf592231053b975f211e4/cmd/mautrix-telegram/legacyprovisioning.go#L393

Use 404 status when not matching a valid identifier
